import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
    <div className={styles.container}>
      <div className={styles.profile_pic}>
        <Image
          src="/images/me.jpg"
          alt="Picture of Sriraj Bura"
          className={styles.img}
          width={250}
          height={250}
        />
      </div>
      <div className={styles.links}>
        <div className={styles.link}>
          <Link href="https://twitter.com/SrirajBura">
            <a>Twitter</a>
          </Link>
        </div>
        <div className={styles.link}>
          <Link href="https://github.com/srirajbura16">
            <a>Github</a>
          </Link>
        </div>
        <div className={styles.link}>
          <Link href="https://www.linkedin.com/in/srirajbura/">
            <a>Linkedin</a>
          </Link>
        </div>
      </div>
    </div>
      </main>
    </div>
  )
}
